<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Preferences</name>
   <tag></tag>
   <elementGuidId>808cd207-7b5e-4b98-9613-de53a3f4fde5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preferences</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome chrome64 win32 no-touch&quot;]/body[1]/div[@class=&quot;topbar-menu-dd responsive-dropdown-menu profile&quot;]/div[@class=&quot;scrollable-dropdown-menu scrollable-dropdown-menu-root dropdown-menu dropdown-menu-root dropdown-menu dropdown-menu-root dropdown dropdown-root responsive-dropdown-menu-root active&quot;]/div[@class=&quot;no-native-scrollbars  scroller-content&quot;]/ul[@class=&quot;dropdown-menu-wrap&quot;]/li[@id=&quot;4d293d07-87e0-4d20-9900-a2b36a69bd8c/c96&quot;]/div[@id=&quot;4d293d07-87e0-4d20-9900-a2b36a69bd8c/c96&quot;]/span[@class=&quot;item-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
