<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_City Illustration</name>
   <tag></tag>
   <elementGuidId>ada7cc67-b6e1-4b5e-b494-e99b30d2726d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@data-title = 'City Illustration' and (text() = 'City Illustration' or . = 'City Illustration')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>exp-item drag-app widget-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>GEOCYL_AP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-favorite-order</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://dsqal060-euw1-20qna20323-globe.3dx-staging.3ds.com:443/globe/webapps/CityIllustrationDesigner/CityIllustrationDesignerWidget.htm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>City Illustration</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isolationlevel</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>https://euw1-20qna20323-apps.3dx-staging.3ds.com:443/enovia/widget/images/MyApps/GEOCYL_AP_AppIcon.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-data</name>
      <type>Main</type>
      <value>{&quot;tenantAware&quot;:true,&quot;x3dPlatformId&quot;:&quot;DSQAL060&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-appid</name>
      <type>Main</type>
      <value>GEOCYL_AP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>071ac37a09d99e65ceacb0b8f1442d639b37543d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-apps</name>
      <type>Main</type>
      <value>[]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>City Illustration</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-apps-ct&quot;)/div[@class=&quot;my-apps-panel items-per-line-5 west&quot;]/div[@class=&quot;compass-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion smooth-scroll apps-accordion&quot;]/div[@class=&quot;compass-scroll-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section my-apps-section&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-container&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section-content&quot;]/ul[@class=&quot;experience-list west&quot;]/li[@class=&quot;exp-item drag-app widget-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
