<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_wux-ui-state-undefine</name>
   <tag></tag>
   <elementGuidId>8c545ce7-af10-4423-9d05-3aff56b20179</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wux-ui-state-undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a description (can be left blank)...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>48</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>512</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;35c65017-3dbb-49c5-8930-0cb2381b4c4c&quot;)/div[@class=&quot;wux-windows-window-mask-content&quot;]/div[@class=&quot;wux-windows-window-maincontent wux-element-contentbox&quot;]/div[@class=&quot;wux-windows-window-content wux-element-contentbox&quot;]/div[@class=&quot;xcity-dialog&quot;]/div[@class=&quot;xcity-label-input&quot;]/div[@class=&quot;wux-controls-abstract wux-controls-editor&quot;]/textarea[@class=&quot;wux-ui-state-undefined&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Techno_3Dcity_DDCityReferential/DataTest/swymInput/Page_Test JCN9 auto/iframe_frame-8tDpnh4A2GPM93U_T</value>
   </webElementProperties>
</WebElementEntity>
