<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3DSpace</name>
   <tag></tag>
   <elementGuidId>40d028ba-cab0-440e-9ada-9722bb424eb8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3DSpace</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-apps-ct&quot;)/div[@class=&quot;my-apps-panel items-per-line-5 north&quot;]/div[@class=&quot;compass-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion smooth-scroll apps-accordion has-scroller&quot;]/div[@class=&quot;compass-scroll-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section my-apps-section&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-container&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section-content&quot;]/ul[@class=&quot;experience-list north&quot;]/li[@class=&quot;exp-item drag-app widget-item&quot;]/div[@class=&quot;title&quot;]</value>
   </webElementProperties>
</WebElementEntity>
