<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_techno</name>
   <tag></tag>
   <elementGuidId>339f223a-380d-4934-b850-30e0ac89fd63</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wux-layouts-treeview-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>techno</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>techno</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;uwa-framed chrome chrome65 win32&quot;]/body[1]/div[@class=&quot;wux-controls-abstract wux-controls-combobox-popup wux-controls-popup&quot;]/div[1]/div[@class=&quot;wux-tree-treelistview wux-controls-combobox-treelistview wux-controls-combobox-treelistview-colors&quot;]/form[1]/div[@class=&quot;wux-datagrid&quot;]/div[@class=&quot;wux-layouts-gridengine wux-ui-is-rendered&quot;]/ul[@class=&quot;wux-ui-stack-h&quot;]/li[2]/div[@class=&quot;wux-layouts-gridengine-scroller-container&quot;]/div[@class=&quot;wux-scroller&quot;]/div[@class=&quot;wux-layouts-gridengine-poolcontainer-rel&quot;]/div[1]/div[@class=&quot;wux-datagrid-cell wux-layouts-treeview-cell wux-datagrid-cell-even wux-controls-combobox-row-preselected wux-datagrid-cell-prehighlighted&quot;]/ul[@class=&quot;wux-ui-stack-h&quot;]/li[@class=&quot;wux-layouts-treeview-node&quot;]/li[@class=&quot;wux-layouts-treeview-label&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Techno_3Dcity_DDCityReferential/DataTest/swymInput/Page_Test JCN9 auto (1)/iframe_frame-8tJ1RsmA2GNm2tCkW</value>
   </webElementProperties>
</WebElementEntity>
