<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_frame-8t0hCeqA2GN6GUWSU</name>
   <tag></tag>
   <elementGuidId>773b217b-6c1c-4469-93bd-0ac15d2d9adb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame-8t0hCeqA2GN6GUWSU1Mb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://euw1-20qna20323-ifwe.3dx-staging.3ds.com/api/widget/frame?id=8t0hCeqA2GN6GUWSU1Mb&amp;uwaUrl=https%3A%2F%2Fdsqal060-euw1-20qna20323-ema%2e3dx-staging%2e3ds%2ecom%3A443%2FXCTWebAppsWidget%2Fwebapps%2FXCTIISWidget%2FXCTIISWidget%2ehtml&amp;appId=XCTIRS_AP&amp;token=f177f344109922623bffe91579c63e6c1039af44&amp;header=0&amp;footer=0&amp;displayEdit=0&amp;autoLaunch=0&amp;widgetDomain=https%3A%2F%2Feuw1-20qna20323-ifwe%2e3dx-staging%2e3ds%2ecom%2F&amp;lang=en&amp;cache=214319942</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame-8t0hCeqA2GN6GUWSU1Mb&quot;)</value>
   </webElementProperties>
</WebElementEntity>
