<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Rendering Studio</name>
   <tag></tag>
   <elementGuidId>ec6d4898-fb82-4587-b0b0-5a45cde79011</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>exp-item drag-app widget-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>XCTIRS_AP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-favorite-order</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://dsqal060-euw1-20qna20323-ema.3dx-staging.3ds.com:443/XCTWebAppsWidget/webapps/XCTIISWidget/XCTIISWidget.html</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Rendering Studio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isolationlevel</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>https://euw1-20qna20323-apps.3dx-staging.3ds.com:443/enovia/widget/images/MyApps/XCTIRS_AP_AppIcon.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-data</name>
      <type>Main</type>
      <value>{&quot;tenantAware&quot;:true,&quot;x3dPlatformId&quot;:&quot;DSQAL060&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-appid</name>
      <type>Main</type>
      <value>XCTIRS_AP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>f177f344109922623bffe91579c63e6c1039af44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-apps</name>
      <type>Main</type>
      <value>[]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rendering Studio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-apps-ct&quot;)/div[@class=&quot;my-apps-panel items-per-line-5 north&quot;]/div[@class=&quot;compass-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion smooth-scroll apps-accordion&quot;]/div[@class=&quot;compass-scroll-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section my-apps-section&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-container&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section-content&quot;]/ul[@class=&quot;experience-list north&quot;]/li[@class=&quot;exp-item drag-app widget-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
