<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DTM2</name>
   <tag></tag>
   <elementGuidId>0e4a787e-4ce4-4ad3-a4e5-764720f71f32</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wux-layouts-treeview-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DTM2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DTM2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referential-panel&quot;)/div[@class=&quot;wux-controls-abstract wux-controls-accordeon-container&quot;]/div[@class=&quot;wux-controls-abstract wux-controls-expander-placeholder&quot;]/div[@class=&quot;wux-controls-expander-container wux-controls-expander-styled wux-controls-expander-toggle&quot;]/div[@class=&quot;wux-controls-expander-body wux-controls-expander-body-toggle&quot;]/div[1]/div[@class=&quot;wux-tree-treelistview&quot;]/form[1]/div[@class=&quot;wux-datagrid&quot;]/div[@class=&quot;wux-layouts-gridengine wux-ui-is-rendered&quot;]/ul[@class=&quot;wux-ui-stack-h&quot;]/li[2]/div[@class=&quot;wux-layouts-gridengine-scroller-container&quot;]/div[@class=&quot;wux-scroller&quot;]/div[@class=&quot;wux-layouts-gridengine-poolcontainer-rel&quot;]/div[1]/div[@class=&quot;wux-datagrid-cell wux-layouts-treeview-cell wux-datagrid-cell-even&quot;]/ul[@class=&quot;wux-ui-stack-h&quot;]/li[@class=&quot;wux-layouts-treeview-node&quot;]/li[@class=&quot;wux-layouts-treeview-label&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Techno_3Dcity_DDCityReferential/OpenDatainCityReferential/Page_Test JCN9 auto/iframe_frame-8t6esv4A2GX9H1Ex4</value>
   </webElementProperties>
</WebElementEntity>
