<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ds-coachmark-close</name>
   <tag></tag>
   <elementGuidId>517edfe3-723c-46be-98a6-72ee3300e037</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ds-coachmark-close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome chrome64 win32 no-touch&quot;]/body[1]/div[@class=&quot;ds-coachmark  uwa-overlay uwa-overlay-root&quot;]/span[@class=&quot;ds-coachmark-close&quot;]</value>
   </webElementProperties>
</WebElementEntity>
