<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_wp-tabview-panel</name>
   <tag></tag>
   <elementGuidId>a2407f0a-c437-4c03-9c34-2499d31108c5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-tabview-panel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_8t0hCeqA2GN6GUWSU1LH&quot;)/div[@class=&quot;moduleWrapper clearfix ifwe-tabview w-541228754&quot;]/div[@class=&quot;wp-tabview&quot;]/div[@class=&quot;wp-tabview-panel&quot;]</value>
   </webElementProperties>
</WebElementEntity>
