<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_frame-8tQ_H0eA2GHCU1EX5</name>
   <tag></tag>
   <elementGuidId>7ab6037f-e5a3-4428-b537-750a0b67ab45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@frameborder = '0' and @width = '100%' and @scrolling = 'auto' and @height = '100%']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame-8tQ_H0eA2GHCU1EX5n7z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://euw1-20qna10404-ifwe.3dx-staging.3ds.com/api/widget/frame?id=8tQ_H0eA2GHCU1EX5n7z&amp;uwaUrl=https%3A%2F%2Feuw1-20qna10404-ifwe%2e3dx-staging%2e3ds%2ecom%2Fresources%2F1%2Fen%2Fwebapps%2FSocialGlobe%2FSocialGlobeUWA%2ehtml&amp;appId=X3DGLOB_AP&amp;token=b9a7c3c812c6ec1f253681ce7463e43de2eb60f1&amp;header=0&amp;footer=0&amp;displayEdit=0&amp;autoLaunch=0&amp;widgetDomain=https%3A%2F%2Feuw1-20qna10404-ifwe%2e3dx-staging%2e3ds%2ecom%2F&amp;lang=en&amp;cache=1635553180</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame-8tQ_H0eA2GHCU1EX5n7z&quot;)</value>
   </webElementProperties>
</WebElementEntity>
