<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Globe Viewer</name>
   <tag></tag>
   <elementGuidId>95b6e83e-ac39-405b-b4a3-d4a18a28305d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'exp-item drag-app widget-item' and @data-title = 'Globe Viewer' and (text() = 'Globe Viewer' or . = 'Globe Viewer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>exp-item drag-app widget-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>X3DGLOB_AP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-favorite-order</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://euw1-20qna10404-ifwe.3dx-staging.3ds.com/resources/1/en/webapps/SocialGlobe/SocialGlobeUWA.html</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Globe Viewer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isolationlevel</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>https://euw1-20qna10404-apps.3dx-staging.3ds.com:443/enovia/widget/images/MyApps/X3DGLOB_AP_AppIcon.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-data</name>
      <type>Main</type>
      <value>{&quot;tenantAware&quot;:false,&quot;x3dPlatformId&quot;:&quot;&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-appid</name>
      <type>Main</type>
      <value>X3DGLOB_AP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>b9a7c3c812c6ec1f253681ce7463e43de2eb60f1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-apps</name>
      <type>Main</type>
      <value>[]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Globe Viewer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-apps-ct&quot;)/div[@class=&quot;my-apps-panel items-per-line-5 west&quot;]/div[@class=&quot;compass-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion smooth-scroll apps-accordion has-scroller&quot;]/div[@class=&quot;compass-scroll-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section my-apps-section&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-container&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section-content&quot;]/ul[@class=&quot;experience-list west&quot;]/li[@class=&quot;exp-item drag-app widget-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
