<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_wux-layouts-treeview-expand</name>
   <tag></tag>
   <elementGuidId>d44dac8f-9702-43da-9f9c-8737b17dc790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'wux-layouts-treeview-expander' and @data-wux-state = 'collapsed' and @ref_element = 'Object Repository/3DSpace/UploadFileInCollabSpace/Page_My First Dashboard/iframe_frame-preview-293675']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wux-layouts-treeview-expander</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wux-state</name>
      <type>Main</type>
      <value>collapsed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;uwa-framed chrome chrome64 win32&quot;]/body[1]/div[@class=&quot;module moduleUwa&quot;]/div[@class=&quot;moduleWrapper&quot;]/div[@class=&quot;moduleContent chrome chrome64 win32 no-touch environment-frame&quot;]/div[@class=&quot;w3ddrive panel-slider&quot;]/div[@class=&quot;panel left&quot;]/div[@class=&quot;w3ddrive drives-panel drives-panel--one-drive-not-granted&quot;]/div[@class=&quot;w3ddrive drives-scroll vertical&quot;]/div[@class=&quot;scroller scroller-root scroller scroller-root&quot;]/div[@class=&quot;no-native-scrollbars  scroller-content scroller-content&quot;]/div[@class=&quot;scrollable-body&quot;]/div[@class=&quot;w3ddrive drives&quot;]/div[@class=&quot;w3ddrive drive&quot;]/div[@class=&quot;wux-tree-treelistview wux-controls-treebase wux-tree-filetreeview w3ddrive drive-tree with-true-root&quot;]/form[1]/div[@class=&quot;wux-datagrid&quot;]/div[@class=&quot;wux-layouts-gridengine wux-ui-is-rendered&quot;]/ul[@class=&quot;wux-ui-stack-h&quot;]/li[2]/div[@class=&quot;wux-layouts-gridengine-scroller-container&quot;]/div[@class=&quot;wux-scroller&quot;]/div[@class=&quot;wux-layouts-gridengine-poolcontainer-rel&quot;]/div[1]/div[@class=&quot;wux-datagrid-cell wux-layouts-treeview-cell wux-datagrid-row-highlighted wux-datagrid-cell-highlighted&quot;]/ul[@class=&quot;wux-ui-stack-h&quot;]/li[@class=&quot;wux-layouts-treeview-node&quot;]/li[@class=&quot;wux-layouts-treeview-expander&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/3DSpace/UploadFileInCollabSpace/Page_My First Dashboard/iframe_frame-preview-293675</value>
   </webElementProperties>
</WebElementEntity>
