<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3DMessaging</name>
   <tag></tag>
   <elementGuidId>d86c96c8-af1a-4754-8b52-db3837c6b74c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3DMessaging</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome chrome64 win32 no-touch&quot;]/body[1]/div[@class=&quot;topbar-menu-dd responsive-dropdown-menu profile&quot;]/div[@class=&quot;scrollable-dropdown-menu scrollable-dropdown-menu-root dropdown-menu dropdown-menu-root dropdown-menu dropdown-menu-root dropdown dropdown-root responsive-dropdown-menu-root active&quot;]/div[@class=&quot;no-native-scrollbars  scroller-content&quot;]/ul[@class=&quot;dropdown-menu-wrap&quot;]/li[@id=&quot;99fdec98-0749-4572-97a7-b182601c1e88/c130&quot;]/div[@id=&quot;99fdec98-0749-4572-97a7-b182601c1e88/c130&quot;]/span[@class=&quot;item-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
