<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Offline</name>
   <tag></tag>
   <elementGuidId>0dcb1b80-f37f-4d2b-9887-e50972bd7e87</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Offline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome chrome64 win32 no-touch&quot;]/body[1]/div[@class=&quot;topbar-menu-dd responsive-dropdown-menu profile&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-root responsive  scroller scroller-root bottom-left&quot;]/div[@class=&quot;no-native-scrollbars  scroller-content&quot;]/ul[@class=&quot;dropdown-menu-wrap&quot;]/li[@id=&quot;99fdec98-0749-4572-97a7-b182601c1e88/c125&quot;]/div[@id=&quot;99fdec98-0749-4572-97a7-b182601c1e88/c125&quot;]/span[@class=&quot;item-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
