<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_frame-8tDpnh4A2GPM93U_T</name>
   <tag></tag>
   <elementGuidId>7090d186-9b8f-454f-bd93-b905147d9de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@frameborder = '0' and @width = '100%' and @scrolling = 'auto' and @height = '100%']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame-8tDpnh4A2GPM93U_TmcX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://euw1-20swi10329-ifwe.3dx-staging.3ds.com/api/widget/frame?id=8tDpnh4A2GPM93U_TmcX&amp;uwaUrl=https%3A%2F%2Feuw1-20swi10329-ifwe%2e3dx-staging%2e3ds%2ecom%2Fresources%2F1%2Fen%2Fwebapps%2FAppFrameContainer%2Fcontainer%2ehtml&amp;appId=X3DPLAW_AP&amp;token=3022af71a4b147550f5a23b0c5b4ab2456fed3fd&amp;header=0&amp;footer=0&amp;displayEdit=0&amp;autoLaunch=0&amp;widgetDomain=https%3A%2F%2Feuw1-20swi10329-ifwe%2e3dx-staging%2e3ds%2ecom%2F&amp;lang=en&amp;cache=310479745</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame-8tDpnh4A2GPM93U_TmcX&quot;)</value>
   </webElementProperties>
</WebElementEntity>
