<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_config_yuhua</name>
   <tag></tag>
   <elementGuidId>14bf240a-f447-460e-9e3f-1d2a904b32e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'wux-datagrid-cell wux-layouts-treeview-cell wux-datagrid-cell-even' and @draggable = 'true' and @title = 'config_yuhua' and @is-editable = 'true' and (text() = 'config_yuhua' or . = 'config_yuhua')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wux-datagrid-cell wux-layouts-treeview-cell wux-datagrid-cell-even</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wux-uuid</name>
      <type>Main</type>
      <value>df66bfcf-45b6-4caf-bb4c-0f347d3e6da5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row-id</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>column-id</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>ds6w:label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>virtual-row-id</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>virtual-column-id</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>config_yuhua</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-editable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>config_yuhua</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table&quot;)/div[@class=&quot;wux-tree-treelistview&quot;]/form[1]/div[@class=&quot;wux-datagrid&quot;]/div[@class=&quot;wux-layouts-gridengine wux-ui-is-rendered&quot;]/ul[@class=&quot;wux-ui-stack-h&quot;]/li[2]/div[@class=&quot;wux-layouts-gridengine-scroller-container&quot;]/div[@class=&quot;wux-scroller&quot;]/div[@class=&quot;wux-layouts-gridengine-poolcontainer-rel&quot;]/div[1]/div[@class=&quot;wux-datagrid-cell wux-layouts-treeview-cell wux-datagrid-cell-even&quot;]</value>
   </webElementProperties>
</WebElementEntity>
