<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_config_yuhuaJidnyasa CHAVA</name>
   <tag></tag>
   <elementGuidId>a42e59eb-86f1-4329-b580-a2959359369d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@draggable = 'true' and (contains(text(), 'config_yuhua') or contains(., 'config_yuhua')) and @ref_element = 'Object Repository/Techno_3Dcity_DDCityReferential/DragDropData/Page_DragDropData/Page_3DspaceData/iframe_frame-8t7MmBOA2GzIFGJzo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3ddrive item inode-item inode-item--focused</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-model_cid</name>
      <type>Main</type>
      <value>c12</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view_cid</name>
      <type>Main</type>
      <value>c37</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>config_yuhua</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;uwa-framed chrome chrome65 win32&quot;]/body[1]/div[@class=&quot;module moduleUwa&quot;]/div[@class=&quot;moduleWrapper&quot;]/div[@class=&quot;moduleContent chrome chrome65 win32 no-touch environment-frame&quot;]/div[@class=&quot;w3ddrive panel-slider&quot;]/div[@class=&quot;panel right active&quot;]/div[@class=&quot;inode-panel w3ddrive&quot;]/div[@class=&quot;scroll-view inode-table-scroll w3ddrive inode-panel__content vertical&quot;]/div[@class=&quot;scroller scroller-root scroller scroller-root&quot;]/div[@class=&quot;no-native-scrollbars  scroller-content scroller-content&quot;]/div[@class=&quot;scrollable-body&quot;]/div[@class=&quot;w3ddrive inodes inode-table w3dx link fixed reveal thumbnails&quot;]/div[@class=&quot;w3ddrive item inode-item inode-item--focused&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Techno_3Dcity_DDCityReferential/DragDropData/Page_DragDropData/Page_3DspaceData/iframe_frame-8t7MmBOA2GzIFGJzo</value>
   </webElementProperties>
</WebElementEntity>
