<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_frame-8t7MmBOA2GzIFGJzo</name>
   <tag></tag>
   <elementGuidId>5e7ad32c-7a34-4066-adbb-3379626f22b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@frameborder = '0' and @width = '100%' and @scrolling = 'auto' and @height = '100%']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame-8t7MmBOA2GzIFGJzom6B</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://euw1-20swi10322-ifwe.3dx-staging.3ds.com/api/widget/frame?id=8t7MmBOA2GzIFGJzom6B&amp;uwaUrl=https%3A%2F%2Fdsqal116-euw1-20swi10322-space%2e3dx-staging%2e3ds%2ecom%3A443%2Fenovia%2Fwebapps%2FW3DDrive%2FW3DSpace%2ehtml&amp;appId=X3DCSMA_AP&amp;token=bdf321cd6c943f16d8f801a7064928b62dc7c844&amp;header=0&amp;footer=0&amp;displayEdit=0&amp;autoLaunch=0&amp;widgetDomain=https%3A%2F%2Feuw1-20swi10322-ifwe%2e3dx-staging%2e3ds%2ecom%2F&amp;lang=en&amp;cache=1282443092</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame-8t7MmBOA2GzIFGJzom6B&quot;)</value>
   </webElementProperties>
</WebElementEntity>
