<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_frame-preview-888e26</name>
   <tag></tag>
   <elementGuidId>feacbb7d-829c-4955-9746-1f16f599d434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id = 'frame-preview-888e26' and @frameborder = '0' and @width = '100%' and @scrolling = 'auto' and @height = '100%']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame-preview-888e26</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://euw1-20qna20327-ifwe.3dx-staging.3ds.com/api/widget/frame?id=preview-888e26&amp;uwaUrl=https%3A%2F%2Feuw1-20qna20327-ifwe%2e3dx-staging%2e3ds%2ecom%2Fresources%2Fen%2F1%2Fwebapps%2FW3DDrive%2FW3DDrive%2ehtml&amp;appId=X3PDRIV_AP&amp;token=972364def40e6766e2f51bc2fd32cd3b495e2373&amp;header=0&amp;footer=0&amp;displayEdit=0&amp;autoLaunch=0&amp;widgetDomain=https%3A%2F%2Feuw1-20qna20327-ifwe%2e3dx-staging%2e3ds%2ecom%2F&amp;lang=en&amp;cache=undefined</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame-preview-888e26&quot;)</value>
   </webElementProperties>
</WebElementEntity>
