<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_City Discover</name>
   <tag></tag>
   <elementGuidId>b22dbb62-7e95-4b82-af85-4e4cbcf26446</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>exp-item drag-app widget-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>GEOCTY_AP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-favorite-order</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://dsqal038-euw1-20swi10301-globe.3dx-staging.3ds.com:443/globe/webapps/UrbanWidget/City3Dplay.html</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>City Discover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isolationlevel</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>https://euw1-20swi10301-apps.3dx-staging.3ds.com:443/enovia/widget/images/MyApps/GEOCTY_AP_AppIcon.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-data</name>
      <type>Main</type>
      <value>{&quot;tenantAware&quot;:true,&quot;x3dPlatformId&quot;:&quot;DSQAL038&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-appid</name>
      <type>Main</type>
      <value>GEOCTY_AP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>f26083172241b49ef3e9d0035ba8ff06a5750df7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-apps</name>
      <type>Main</type>
      <value>[]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>City Discover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-apps-ct&quot;)/div[@class=&quot;my-apps-panel items-per-line-5 west&quot;]/div[@class=&quot;compass-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion smooth-scroll apps-accordion has-scroller&quot;]/div[@class=&quot;compass-scroll-accordion-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section my-apps-section&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-container&quot;]/div[@class=&quot;compass-scroll-accordion-section-content-wrapper&quot;]/div[@class=&quot;compass-scroll-accordion-section-content&quot;]/ul[@class=&quot;experience-list west&quot;]/li[@class=&quot;exp-item drag-app widget-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
