<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>c6c348ed-76f2-4839-b3a7-1054d214feac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;xCityViewer&quot;)/canvas[1][count(. | //canvas[@ref_element = 'Object Repository/Techno_3Dcity_DDCityReferential/DragDropData/Page_DragDropData/Page_Data/iframe_frame-8t6esv4A2GX9H1Ex4']) = count(//canvas[@ref_element = 'Object Repository/Techno_3Dcity_DDCityReferential/DragDropData/Page_DragDropData/Page_Data/iframe_frame-8t6esv4A2GX9H1Ex4'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>602</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>289</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xCityViewer&quot;)/canvas[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Techno_3Dcity_DDCityReferential/DragDropData/Page_DragDropData/Page_Data/iframe_frame-8t6esv4A2GX9H1Ex4</value>
   </webElementProperties>
</WebElementEntity>
